### ISSUE TITLE
indent question

### ISSUE THREAD

**Issue by copdips** [societe-generale/spintest#14]
Hello,

Just would like to know if there's an identation issue for the `else` clause at:

https://github.com/societe-generale/spintest/blob/master/spintest/task.py#L114
https://github.com/societe-generale/spintest/blob/master/spintest/task.py#L121

**Comment by bew** [comment]
I don't think so, it's a feature of the [`for` statement](https://docs.python.org/3/reference/compound_stmts.html#for) in python, it supports the optional syntax `["else" ":" suite]`.

basically:
```py
for i in some_iterable:
    print("iterable is not empty..")
else:
    print("iterable is empty")
```
is similar to:
```py
if some_iterable:
    for i in some_iterable:
        print("iterable is not empty..")
else:
   print("iterable is empty")
```
BUT without trying to consume `some_iterable` for the first if.

**Comment by copdips** [comment]
Okey, I think understand better now, it's specially for comparing two lists.

**Comment by bew** [comment]
> ```python
> In [5]: some_iterable = [1, 2]
> 
> In [6]: for i in some_iterable:
>    ...:     print("iterable is not empty..")
>    ...: else:
>    ...:     print("iterable is empty")
>    ...: 
> iterable is not empty..
> iterable is not empty..
> iterable is empty
> ```

Hmm actually it seems to be (a bit) counter intuitive, and is more similar to:
```py
for i in some_iterable:
    print("iterable is not empty..")
print("iterable is empty")
```
I'm not sure why that syntax even exists then....

I've never used it myself.

> Just would like to know is this what you expected for spintest ?

NOTE that I didn't write this part, and we don't do much more development since this was originally written as it works well for how we use it.
If you think there's a problem with the behavior, feel free to open an issue about it!

**Comment by bew** [comment]
> @bew could we compare 2 lists in this way ?
> 
> ```python
> for i in range(len(body)):
>     if not self._compare_body(body[i], expected[i]):
>         return False
> return True
> ```

In an imperative way, yes, that's another way to do it.

If you want to have some fun with functional programming, you could also write this:
```py
it1 = [654, 568, 12, 2]
it2 = [654, 568, 12, 2]

def compare_item(item1, item2):
    return item1 == item2

return all(map(lambda t: compare_item(*t), zip(it1, it2)))
```

**Comment by copdips** [comment]
@bew ,
Thanks for your helpful comments, I will close this issue, as the current code works.
But if we can use more friendly syntax for the list comparaison as shown by your examples, it would be great.
